// Multi-language translation system for admin panel
// Supported languages: English (base), Spanish, Italian, French, German

export type Language = 'en' | 'es' | 'it' | 'fr' | 'de'

export interface Translations {
  common: { loading: string; save: string; cancel: string; delete: string; edit: string; add: string; create: string; update: string; search: string; filter: string; actions: string; status: string; active: string; inactive: string; yes: string; no: string; back: string; next: string; previous: string; close: string; confirm: string; success: string; error: string; warning: string }
  nav: { dashboard: string; products: string; orders: string; customers: string; users: string; analytics: string; settings: string; logout: string; collections: string; categories: string; inventory: string; customerGroups: string; promotions: string; giftCards: string; pricing: string; regions: string; shipping: string; salesChannels: string; taxes: string; payments: string; apiKeys: string }
  dashboard: { title: string; subtitle: string; revenue: string; orders: string; products: string; customers: string; totalRevenue: string; totalOrders: string; totalProducts: string; totalCustomers: string; today: string; activeProducts: string; registeredUsers: string; todayPerformance: string; thisMonth: string; orderStatusOverview: string; pending: string; processing: string; shipped: string; delivered: string; cancelled: string; revenueChange: string; ordersChange: string; selectPeriod: string; thisYear: string; thisWeek: string; customRange: string; from: string; to: string; cancel: string; applyRange: string; startDate: string; endDate: string; applyFilter: string; recentOrders: string; topProducts: string; orderNumber: string; customer: string; date: string; amount: string; orderStatus: string; viewAll: string; order: string; topSellingProducts: string; unitsSold: string; revenueLabel: string; statusDelivered: string; statusShipped: string; statusProcessing: string; statusPending: string; statusCancelled: string; statusCompleted: string }
  products: { title: string; addProduct: string; editProduct: string; productName: string; description: string; price: string; stock: string; sku: string; activeProduct: string; createProduct: string; updateProduct: string; deleteConfirm: string; filterPlaceholder: string; priceFilter: string; allProducts: string }
  orders: { title: string; orderId: string; customer: string; date: string; total: string; status: string; paymentStatus: string; pending: string; processing: string; shipped: string; delivered: string; cancelled: string; paid: string; unpaid: string; failed: string; refunded: string; viewDetails: string; updateStatus: string; filterPlaceholder: string; totalFilter: string; guest: string; noRecords: string; noRecordsDescription: string; allOrders: string; completed: string }
  users: { title: string; userId: string; email: string; fullName: string; admin: string; active: string; createdAt: string; lastOrder: string; totalSpent: string; addUser: string; editUser: string; deleteConfirm: string; filterPlaceholder: string }
  auth: { login: string; logout: string; email: string; password: string; loginButton: string; loginTitle: string; loginSubtitle: string; invalidCredentials: string; sessionExpired: string }
  messages: { saveSuccess: string; saveError: string; deleteSuccess: string; deleteError: string; loadError: string; noData: string; loadingMore: string; allLoaded: string }
  apiKeys: { title: string; subtitle: string; name: string; key: string; created: string; addKey: string }
  categories: { title: string; subtitle: string; name: string; slug: string; description: string; imageUrl: string; edit: string; delete: string; addCategory: string; editCategory: string; nameRequired: string; deleteConfirm: string; noDescription: string; noCategories: string }
  collections: { title: string; subtitle: string; name: string; products: string; status: string; addCollection: string }
  customerGroups: { title: string; subtitle: string; totalGroups: string; totalSegments: string; inGroups: string; inSegments: string; createGroup: string; createSegment: string }
  giftCards: { title: string; subtitle: string; code: string; balance: string; originalValue: string; addGiftCard: string }
  inventory: { title: string; subtitle: string; product: string; available: string; reserved: string; location: string }
  payments: { title: string; subtitle: string; totalPayments: string; totalCaptured: string; transaction: string; amount: string; date: string }
  pricing: { title: string; subtitle: string; name: string; type: string; products: string; addPriceList: string }
  promotions: { title: string; subtitle: string; totalPromotions: string; active: string; expired: string; totalUses: string; createPromotion: string }
  regions: { title: string; subtitle: string; name: string; countries: string; currency: string; addRegion: string }
  salesChannels: { title: string; subtitle: string; name: string; description: string; products: string; addChannel: string }
  settings: { title: string; subtitle: string; storeDetails: string; storeName: string; storeEmail: string; storePhone: string; saveChanges: string }
  shipping: { title: string; subtitle: string; name: string; region: string; price: string; addShipping: string }
  taxes: { title: string; subtitle: string; name: string; region: string; rate: string; addTax: string }
  login: { title: string; subtitle: string; email: string; password: string; loginButton: string; forgotPassword: string }
}

const translations: Record<Language, Translations> = {
  en: {
    common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', create: 'Create', update: 'Update', search: 'Search', filter: 'Filter', actions: 'Actions', status: 'Status', active: 'Active', inactive: 'Inactive', yes: 'Yes', no: 'No', back: 'Back', next: 'Next', previous: 'Previous', close: 'Close', confirm: 'Confirm', success: 'Success', error: 'Error', warning: 'Warning' },
    nav: { dashboard: 'Dashboard', products: 'Products', orders: 'Orders', customers: 'Customers', users: 'Users', analytics: 'Analytics', settings: 'Settings', logout: 'Logout', collections: 'Collections', categories: 'Categories', inventory: 'Inventory', customerGroups: 'Customer Groups', promotions: 'Promotions', giftCards: 'Gift Cards', pricing: 'Pricing', regions: 'Regions', shipping: 'Shipping', salesChannels: 'Sales Channels', taxes: 'Taxes', payments: 'Payments', apiKeys: 'API Keys' },
    dashboard: { title: 'Dashboard', subtitle: 'Overview of your store\'s performance', revenue: 'Revenue', orders: 'Orders', products: 'Products', customers: 'Customers', totalRevenue: 'Total Revenue', totalOrders: 'Total Orders', totalProducts: 'Total Products', totalCustomers: 'Total Customers', today: 'today', activeProducts: 'Active products', registeredUsers: 'Registered users', todayPerformance: 'Today\'s Performance', thisMonth: 'This Month', orderStatusOverview: 'Order Status Overview', pending: 'Pending', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled', revenueChange: 'vs last period', ordersChange: 'vs last period', selectPeriod: 'Select Period', thisYear: 'This Year', thisWeek: 'This Week', customRange: 'Custom Date Range', from: 'From', to: 'To', cancel: 'Cancel', applyRange: 'Apply Range', startDate: 'Start Date', endDate: 'End Date', applyFilter: 'Apply Filter', recentOrders: 'Recent Orders', topProducts: 'Top Products', orderNumber: 'Order #', customer: 'Customer', date: 'Date', amount: 'Amount', orderStatus: 'Status', viewAll: 'View All', order: 'Order', topSellingProducts: 'Top Selling Products', unitsSold: 'units sold', revenueLabel: 'Revenue', statusDelivered: 'Delivered', statusShipped: 'Shipped', statusProcessing: 'Processing', statusPending: 'Pending', statusCancelled: 'Cancelled', statusCompleted: 'Completed' },
    products: { title: 'Products', addProduct: 'Add Product', editProduct: 'Edit Product', productName: 'Product Name', description: 'Description', price: 'Price', stock: 'Stock', sku: 'SKU', activeProduct: 'Active Product', createProduct: 'Create Product', updateProduct: 'Update Product', deleteConfirm: 'Are you sure you want to delete this product?', filterPlaceholder: 'Filter...', priceFilter: '>520, <850, =30...', allProducts: 'All products loaded' },
    orders: { title: 'Orders', orderId: 'Order ID', customer: 'Customer', date: 'Date', total: 'Total', status: 'Status', paymentStatus: 'Payment Status', pending: 'Pending', processing: 'Processing', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled', paid: 'Paid', unpaid: 'Unpaid', failed: 'Failed', refunded: 'Refunded', viewDetails: 'View Details', updateStatus: 'Update Status', filterPlaceholder: 'Filter...', totalFilter: '>520, <850, =30...', guest: 'Guest', noRecords: 'No records', noRecordsDescription: 'Your orders will show up here.', allOrders: 'All orders loaded', completed: 'Completed' },
    users: { title: 'Users', userId: 'User ID', email: 'Email', fullName: 'Full Name', admin: 'Admin', active: 'Active', createdAt: 'Created', lastOrder: 'Last Order', totalSpent: 'Total Spent', addUser: 'Add User', editUser: 'Edit User', deleteConfirm: 'Are you sure you want to delete this user?', filterPlaceholder: 'Filter...' },
    auth: { login: 'Login', logout: 'Logout', email: 'Email', password: 'Password', loginButton: 'Sign In', loginTitle: 'Admin Login', loginSubtitle: 'Sign in to your admin account', invalidCredentials: 'Invalid credentials', sessionExpired: 'Session expired. Please login again.' },
    messages: { saveSuccess: 'Saved successfully', saveError: 'Failed to save', deleteSuccess: 'Deleted successfully', deleteError: 'Failed to delete', loadError: 'Failed to load data', noData: 'No data available', loadingMore: 'Loading more...', allLoaded: 'All data loaded' },
    apiKeys: { title: 'API Keys', subtitle: 'Manage API keys and access tokens', name: 'Name', key: 'Key', created: 'Created', addKey: 'Add Key' },
    categories: { title: 'Categories', subtitle: 'Organize your products', name: 'Name', slug: 'Slug', description: 'Description', imageUrl: 'Image URL', edit: 'Edit', delete: 'Delete', addCategory: 'Add Category', editCategory: 'Edit Category', nameRequired: 'Name and slug are required', deleteConfirm: 'Are you sure you want to delete this category?', noDescription: 'No description', noCategories: 'No categories found' },
    collections: { title: 'Collections', subtitle: 'Organize products into collections', name: 'Name', products: 'Products', status: 'Status', addCollection: 'Add Collection' },
    customerGroups: { title: 'Customer Groups', subtitle: 'Manage customer groups and segments', totalGroups: 'Total Groups', totalSegments: 'Total Segments', inGroups: 'In Groups', inSegments: 'In Segments', createGroup: 'Create Group', createSegment: 'Create Segment' },
    giftCards: { title: 'Gift Cards', subtitle: 'Manage gift cards and balances', code: 'Code', balance: 'Balance', originalValue: 'Original Value', addGiftCard: 'Add Gift Card' },
    inventory: { title: 'Inventory', subtitle: 'Manage stock levels and locations', product: 'Product', available: 'Available', reserved: 'Reserved', location: 'Location' },
    payments: { title: 'Payments', subtitle: 'View and manage all payment transactions', totalPayments: 'Total Payments', totalCaptured: 'Total Captured', transaction: 'Transaction', amount: 'Amount', date: 'Date' },
    pricing: { title: 'Pricing', subtitle: 'Manage price lists and customer-specific pricing', name: 'Name', type: 'Type', products: 'Products', addPriceList: 'Add Price List' },
    promotions: { title: 'Promotions', subtitle: 'Manage discounts and promotions', totalPromotions: 'Total Promotions', active: 'Active', expired: 'Expired', totalUses: 'Total Uses', createPromotion: 'Create Promotion' },
    regions: { title: 'Regions', subtitle: 'Manage geographic regions and currencies', name: 'Name', countries: 'Countries', currency: 'Currency', addRegion: 'Add Region' },
    salesChannels: { title: 'Sales Channels', subtitle: 'Manage where your products are sold', name: 'Name', description: 'Description', products: 'Products', addChannel: 'Add Channel' },
    settings: { title: 'Settings', subtitle: 'Manage your store settings and preferences', storeDetails: 'Store Details', storeName: 'Store Name', storeEmail: 'Store Email', storePhone: 'Store Phone', saveChanges: 'Save Changes' },
    shipping: { title: 'Shipping', subtitle: 'Manage shipping options and rates', name: 'Name', region: 'Region', price: 'Price', addShipping: 'Add Shipping Option' },
    taxes: { title: 'Taxes', subtitle: 'Manage tax rates and rules', name: 'Name', region: 'Region', rate: 'Rate', addTax: 'Add Tax' },
    login: { title: 'Admin Login', subtitle: 'Shop Administration Dashboard', email: 'Email', password: 'Password', loginButton: 'Login', forgotPassword: 'Forgot Password?' }
  },
  es: {
    common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', add: 'Añadir', create: 'Crear', update: 'Actualizar', search: 'Buscar', filter: 'Filtrar', actions: 'Acciones', status: 'Estado', active: 'Activo', inactive: 'Inactivo', yes: 'Sí', no: 'No', back: 'Atrás', next: 'Siguiente', previous: 'Anterior', close: 'Cerrar', confirm: 'Confirmar', success: 'Éxito', error: 'Error', warning: 'Advertencia' },
    nav: { dashboard: 'Panel de Control', products: 'Productos', orders: 'Pedidos', customers: 'Clientes', users: 'Usuarios', analytics: 'Análisis', settings: 'Configuración', logout: 'Cerrar Sesión', collections: 'Colecciones', categories: 'Categorías', inventory: 'Inventario', customerGroups: 'Grupos de Clientes', promotions: 'Promociones', giftCards: 'Tarjetas de Regalo', pricing: 'Precios', regions: 'Regiones', shipping: 'Envío', salesChannels: 'Canales de Venta', taxes: 'Impuestos', payments: 'Pagos', apiKeys: 'Claves API' },
    dashboard: { title: 'Panel de Control', subtitle: 'Resumen del rendimiento de tu tienda', revenue: 'Ingresos', orders: 'Pedidos', products: 'Productos', customers: 'Clientes', totalRevenue: 'Ingresos Totales', totalOrders: 'Pedidos Totales', totalProducts: 'Productos Totales', totalCustomers: 'Clientes Totales', today: 'hoy', activeProducts: 'Productos activos', registeredUsers: 'Usuarios registrados', todayPerformance: 'Rendimiento de Hoy', thisMonth: 'Este Mes', orderStatusOverview: 'Resumen de Estado del Pedido', pending: 'Pendiente', processing: 'En Procesamiento', shipped: 'Enviado', delivered: 'Entregado', cancelled: 'Cancelado', revenueChange: 'vs período anterior', ordersChange: 'vs período anterior', selectPeriod: 'Seleccionar Período', thisYear: 'Este Año', thisWeek: 'Esta Semana', customRange: 'Rango de Fechas Personalizado', from: 'Desde', to: 'Hasta', cancel: 'Cancelar', applyRange: 'Aplicar Rango', startDate: 'Fecha de Inicio', endDate: 'Fecha de Fin', applyFilter: 'Aplicar Filtro', recentOrders: 'Pedidos Recientes', topProducts: 'Productos Principales', orderNumber: 'Pedido #', customer: 'Cliente', date: 'Fecha', amount: 'Cantidad', orderStatus: 'Estado', viewAll: 'Ver Todo', order: 'Pedido', topSellingProducts: 'Productos Más Vendidos', unitsSold: 'unidades vendidas', revenueLabel: 'Ingresos', statusDelivered: 'Entregado', statusShipped: 'Enviado', statusProcessing: 'En Procesamiento', statusPending: 'Pendiente', statusCancelled: 'Cancelado', statusCompleted: 'Completado' },
    products: { title: 'Productos', addProduct: 'Añadir Producto', editProduct: 'Editar Producto', productName: 'Nombre del Producto', description: 'Descripción', price: 'Precio', stock: 'Stock', sku: 'SKU', activeProduct: 'Producto Activo', createProduct: 'Crear Producto', updateProduct: 'Actualizar Producto', deleteConfirm: '¿Estás seguro de que quieres eliminar este producto?', filterPlaceholder: 'Filtrar...', priceFilter: '>520, <850, =30...', allProducts: 'Todos los productos cargados' },
    orders: { title: 'Pedidos', orderId: 'ID de Pedido', customer: 'Cliente', date: 'Fecha', total: 'Total', status: 'Estado', paymentStatus: 'Estado de Pago', pending: 'Pendiente', processing: 'En Procesamiento', shipped: 'Enviado', delivered: 'Entregado', cancelled: 'Cancelado', paid: 'Pagado', unpaid: 'No Pagado', failed: 'Fallido', refunded: 'Reembolsado', viewDetails: 'Ver Detalles', updateStatus: 'Actualizar Estado', filterPlaceholder: 'Filtrar...', totalFilter: '>520, <850, =30...', guest: 'Invitado', noRecords: 'No hay registros', noRecordsDescription: 'Tus pedidos aparecerán aquí.', allOrders: 'Todos los pedidos cargados', completed: 'Completado' },
    users: { title: 'Usuarios', userId: 'ID de Usuario', email: 'Email', fullName: 'Nombre Completo', admin: 'Administrador', active: 'Activo', createdAt: 'Creado', lastOrder: 'Último Pedido', totalSpent: 'Total Gastado', addUser: 'Añadir Usuario', editUser: 'Editar Usuario', deleteConfirm: '¿Estás seguro de que quieres eliminar este usuario?', filterPlaceholder: 'Filtrar...' },
    auth: { login: 'Iniciar Sesión', logout: 'Cerrar Sesión', email: 'Email', password: 'Contraseña', loginButton: 'Entrar', loginTitle: 'Acceso de Administrador', loginSubtitle: 'Inicia sesión en tu cuenta de administrador', invalidCredentials: 'Credenciales inválidas', sessionExpired: 'Sesión expirada. Por favor inicia sesión de nuevo.' },
    messages: { saveSuccess: 'Guardado exitosamente', saveError: 'Error al guardar', deleteSuccess: 'Eliminado exitosamente', deleteError: 'Error al eliminar', loadError: 'Error al cargar datos', noData: 'No hay datos disponibles', loadingMore: 'Cargando más...', allLoaded: 'Todos los datos cargados' },
    apiKeys: { title: 'Claves API', subtitle: 'Gestiona claves API y tokens de acceso', name: 'Nombre', key: 'Clave', created: 'Creado', addKey: 'Añadir Clave' },
    categories: { title: 'Categorías', subtitle: 'Organiza tus productos', name: 'Nombre', slug: 'Slug', description: 'Descripción', imageUrl: 'URL de Imagen', edit: 'Editar', delete: 'Eliminar', addCategory: 'Añadir Categoría', editCategory: 'Editar Categoría', nameRequired: 'Nombre y slug son requeridos', deleteConfirm: '¿Estás seguro de que quieres eliminar esta categoría?', noDescription: 'Sin descripción', noCategories: 'No se encontraron categorías' },
    collections: { title: 'Colecciones', subtitle: 'Organiza productos en colecciones', name: 'Nombre', products: 'Productos', status: 'Estado', addCollection: 'Añadir Colección' },
    customerGroups: { title: 'Grupos de Clientes', subtitle: 'Gestiona grupos de clientes y segmentos', totalGroups: 'Grupos Totales', totalSegments: 'Segmentos Totales', inGroups: 'En Grupos', inSegments: 'En Segmentos', createGroup: 'Crear Grupo', createSegment: 'Crear Segmento' },
    giftCards: { title: 'Tarjetas de Regalo', subtitle: 'Gestiona tarjetas de regalo y saldos', code: 'Código', balance: 'Saldo', originalValue: 'Valor Original', addGiftCard: 'Añadir Tarjeta de Regalo' },
    inventory: { title: 'Inventario', subtitle: 'Gestiona niveles de stock y ubicaciones', product: 'Producto', available: 'Disponible', reserved: 'Reservado', location: 'Ubicación' },
    payments: { title: 'Pagos', subtitle: 'Ver y gestionar todas las transacciones de pago', totalPayments: 'Pagos Totales', totalCaptured: 'Total Capturado', transaction: 'Transacción', amount: 'Cantidad', date: 'Fecha' },
    pricing: { title: 'Precios', subtitle: 'Gestiona listas de precios y precios específicos del cliente', name: 'Nombre', type: 'Tipo', products: 'Productos', addPriceList: 'Añadir Lista de Precios' },
    promotions: { title: 'Promociones', subtitle: 'Gestiona descuentos y promociones', totalPromotions: 'Promociones Totales', active: 'Activo', expired: 'Expirado', totalUses: 'Usos Totales', createPromotion: 'Crear Promoción' },
    regions: { title: 'Regiones', subtitle: 'Gestiona regiones geográficas y monedas', name: 'Nombre', countries: 'Países', currency: 'Moneda', addRegion: 'Añadir Región' },
    salesChannels: { title: 'Canales de Venta', subtitle: 'Gestiona dónde se venden tus productos', name: 'Nombre', description: 'Descripción', products: 'Productos', addChannel: 'Añadir Canal' },
    settings: { title: 'Configuración', subtitle: 'Gestiona tu tienda y preferencias', storeDetails: 'Detalles de la Tienda', storeName: 'Nombre de la Tienda', storeEmail: 'Email de la Tienda', storePhone: 'Teléfono de la Tienda', saveChanges: 'Guardar Cambios' },
    shipping: { title: 'Envío', subtitle: 'Gestiona opciones y tarifas de envío', name: 'Nombre', region: 'Región', price: 'Precio', addShipping: 'Añadir Opción de Envío' },
    taxes: { title: 'Impuestos', subtitle: 'Gestiona tasas y reglas de impuestos', name: 'Nombre', region: 'Región', rate: 'Tasa', addTax: 'Añadir Impuesto' },
    login: { title: 'Acceso de Administrador', subtitle: 'Panel de Administración de la Tienda', email: 'Email', password: 'Contraseña', loginButton: 'Entrar', forgotPassword: '¿Olvidaste tu Contraseña?' }
  },
  it: {
    common: { loading: 'Caricamento...', save: 'Salva', cancel: 'Annulla', delete: 'Elimina', edit: 'Modifica', add: 'Aggiungi', create: 'Crea', update: 'Aggiorna', search: 'Cerca', filter: 'Filtro', actions: 'Azioni', status: 'Stato', active: 'Attivo', inactive: 'Inattivo', yes: 'Sì', no: 'No', back: 'Indietro', next: 'Successivo', previous: 'Precedente', close: 'Chiudi', confirm: 'Conferma', success: 'Successo', error: 'Errore', warning: 'Avviso' },
    nav: { dashboard: 'Pannello di Controllo', products: 'Prodotti', orders: 'Ordini', customers: 'Clienti', users: 'Utenti', analytics: 'Analitiche', settings: 'Impostazioni', logout: 'Esci', collections: 'Collezioni', categories: 'Categorie', inventory: 'Inventario', customerGroups: 'Gruppi di Clienti', promotions: 'Promozioni', giftCards: 'Carte Regalo', pricing: 'Prezzi', regions: 'Regioni', shipping: 'Spedizione', salesChannels: 'Canali di Vendita', taxes: 'Tasse', payments: 'Pagamenti', apiKeys: 'Chiavi API' },
    dashboard: { title: 'Pannello di Controllo', subtitle: 'Panoramica delle prestazioni del tuo negozio', revenue: 'Ricavi', orders: 'Ordini', products: 'Prodotti', customers: 'Clienti', totalRevenue: 'Ricavi Totali', totalOrders: 'Ordini Totali', totalProducts: 'Prodotti Totali', totalCustomers: 'Clienti Totali', today: 'oggi', activeProducts: 'Prodotti attivi', registeredUsers: 'Utenti registrati', todayPerformance: 'Prestazioni Odierne', thisMonth: 'Questo Mese', orderStatusOverview: 'Panoramica dello Stato dell\'Ordine', pending: 'In Sospeso', processing: 'In Elaborazione', shipped: 'Spedito', delivered: 'Consegnato', cancelled: 'Annullato', revenueChange: 'vs periodo precedente', ordersChange: 'vs periodo precedente', selectPeriod: 'Seleziona Periodo', thisYear: 'Questo Anno', thisWeek: 'Questa Settimana', customRange: 'Intervallo di Date Personalizzato', from: 'Da', to: 'A', cancel: 'Annulla', applyRange: 'Applica Intervallo', startDate: 'Data di Inizio', endDate: 'Data di Fine', applyFilter: 'Applica Filtro', recentOrders: 'Ordini Recenti', topProducts: 'Prodotti Principali', orderNumber: 'Ordine #', customer: 'Cliente', date: 'Data', amount: 'Importo', orderStatus: 'Stato', viewAll: 'Visualizza Tutto', order: 'Ordine', topSellingProducts: 'Prodotti Più Venduti', unitsSold: 'unità vendute', revenueLabel: 'Ricavi', statusDelivered: 'Consegnato', statusShipped: 'Spedito', statusProcessing: 'In Elaborazione', statusPending: 'In Sospeso', statusCancelled: 'Annullato', statusCompleted: 'Completato' },
    products: { title: 'Prodotti', addProduct: 'Aggiungi Prodotto', editProduct: 'Modifica Prodotto', productName: 'Nome Prodotto', description: 'Descrizione', price: 'Prezzo', stock: 'Magazzino', sku: 'SKU', activeProduct: 'Prodotto Attivo', createProduct: 'Crea Prodotto', updateProduct: 'Aggiorna Prodotto', deleteConfirm: 'Sei sicuro di voler eliminare questo prodotto?', filterPlaceholder: 'Filtro...', priceFilter: '>520, <850, =30...', allProducts: 'Tutti i prodotti caricati' },
    orders: { title: 'Ordini', orderId: 'ID Ordine', customer: 'Cliente', date: 'Data', total: 'Totale', status: 'Stato', paymentStatus: 'Stato Pagamento', pending: 'In Sospeso', processing: 'In Elaborazione', shipped: 'Spedito', delivered: 'Consegnato', cancelled: 'Annullato', paid: 'Pagato', unpaid: 'Non Pagato', failed: 'Non Riuscito', refunded: 'Rimborsato', viewDetails: 'Visualizza Dettagli', updateStatus: 'Aggiorna Stato', filterPlaceholder: 'Filtro...', totalFilter: '>520, <850, =30...', guest: 'Ospite', noRecords: 'Nessun record', noRecordsDescription: 'I tuoi ordini appariranno qui.', allOrders: 'Tutti gli ordini caricati', completed: 'Completato' },
    users: { title: 'Utenti', userId: 'ID Utente', email: 'Email', fullName: 'Nome Completo', admin: 'Amministratore', active: 'Attivo', createdAt: 'Creato', lastOrder: 'Ultimo Ordine', totalSpent: 'Totale Speso', addUser: 'Aggiungi Utente', editUser: 'Modifica Utente', deleteConfirm: 'Sei sicuro di voler eliminare questo utente?', filterPlaceholder: 'Filtro...' },
    auth: { login: 'Accedi', logout: 'Esci', email: 'Email', password: 'Password', loginButton: 'Accedi', loginTitle: 'Accesso Amministratore', loginSubtitle: 'Accedi al tuo account amministratore', invalidCredentials: 'Credenziali non valide', sessionExpired: 'Sessione scaduta. Per favore accedi di nuovo.' },
    messages: { saveSuccess: 'Salvato con successo', saveError: 'Errore nel salvataggio', deleteSuccess: 'Eliminato con successo', deleteError: 'Errore nell\'eliminazione', loadError: 'Errore nel caricamento dei dati', noData: 'Nessun dato disponibile', loadingMore: 'Caricamento in corso...', allLoaded: 'Tutti i dati caricati' },
    apiKeys: { title: 'Chiavi API', subtitle: 'Gestisci chiavi API e token di accesso', name: 'Nome', key: 'Chiave', created: 'Creato', addKey: 'Aggiungi Chiave' },
    categories: { title: 'Categorie', subtitle: 'Organizza i tuoi prodotti', name: 'Nome', slug: 'Slug', description: 'Descrizione', imageUrl: 'URL Immagine', edit: 'Modifica', delete: 'Elimina', addCategory: 'Aggiungi Categoria', editCategory: 'Modifica Categoria', nameRequired: 'Nome e slug sono obbligatori', deleteConfirm: 'Sei sicuro di voler eliminare questa categoria?', noDescription: 'Nessuna descrizione', noCategories: 'Nessuna categoria trovata' },
    collections: { title: 'Collezioni', subtitle: 'Organizza i prodotti in collezioni', name: 'Nome', products: 'Prodotti', status: 'Stato', addCollection: 'Aggiungi Collezione' },
    customerGroups: { title: 'Gruppi di Clienti', subtitle: 'Gestisci gruppi di clienti e segmenti', totalGroups: 'Gruppi Totali', totalSegments: 'Segmenti Totali', inGroups: 'In Gruppi', inSegments: 'In Segmenti', createGroup: 'Crea Gruppo', createSegment: 'Crea Segmento' },
    giftCards: { title: 'Carte Regalo', subtitle: 'Gestisci carte regalo e saldi', code: 'Codice', balance: 'Saldo', originalValue: 'Valore Originale', addGiftCard: 'Aggiungi Carta Regalo' },
    inventory: { title: 'Inventario', subtitle: 'Gestisci livelli di magazzino e ubicazioni', product: 'Prodotto', available: 'Disponibile', reserved: 'Riservato', location: 'Ubicazione' },
    payments: { title: 'Pagamenti', subtitle: 'Visualizza e gestisci tutte le transazioni di pagamento', totalPayments: 'Pagamenti Totali', totalCaptured: 'Totale Catturato', transaction: 'Transazione', amount: 'Importo', date: 'Data' },
    pricing: { title: 'Prezzi', subtitle: 'Gestisci listini prezzi e prezzi specifici per clienti', name: 'Nome', type: 'Tipo', products: 'Prodotti', addPriceList: 'Aggiungi Listino Prezzi' },
    promotions: { title: 'Promozioni', subtitle: 'Gestisci sconti e promozioni', totalPromotions: 'Promozioni Totali', active: 'Attivo', expired: 'Scaduto', totalUses: 'Utilizzi Totali', createPromotion: 'Crea Promozione' },
    regions: { title: 'Regioni', subtitle: 'Gestisci regioni geografiche e valute', name: 'Nome', countries: 'Paesi', currency: 'Valuta', addRegion: 'Aggiungi Regione' },
    salesChannels: { title: 'Canali di Vendita', subtitle: 'Gestisci dove vengono venduti i tuoi prodotti', name: 'Nome', description: 'Descrizione', products: 'Prodotti', addChannel: 'Aggiungi Canale' },
    settings: { title: 'Impostazioni', subtitle: 'Gestisci le impostazioni e le preferenze del negozio', storeDetails: 'Dettagli del Negozio', storeName: 'Nome del Negozio', storeEmail: 'Email del Negozio', storePhone: 'Telefono del Negozio', saveChanges: 'Salva Modifiche' },
    shipping: { title: 'Spedizione', subtitle: 'Gestisci opzioni e tariffe di spedizione', name: 'Nome', region: 'Regione', price: 'Prezzo', addShipping: 'Aggiungi Opzione di Spedizione' },
    taxes: { title: 'Tasse', subtitle: 'Gestisci aliquote e regole fiscali', name: 'Nome', region: 'Regione', rate: 'Aliquota', addTax: 'Aggiungi Tassa' },
    login: { title: 'Accesso Amministratore', subtitle: 'Pannello di Amministrazione del Negozio', email: 'Email', password: 'Password', loginButton: 'Accedi', forgotPassword: 'Password Dimenticata?' }
  },
  fr: {
    common: { loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', add: 'Ajouter', create: 'Créer', update: 'Mettre à jour', search: 'Rechercher', filter: 'Filtrer', actions: 'Actions', status: 'Statut', active: 'Actif', inactive: 'Inactif', yes: 'Oui', no: 'Non', back: 'Retour', next: 'Suivant', previous: 'Précédent', close: 'Fermer', confirm: 'Confirmer', success: 'Succès', error: 'Erreur', warning: 'Avertissement' },
    nav: { dashboard: 'Tableau de Bord', products: 'Produits', orders: 'Commandes', customers: 'Clients', users: 'Utilisateurs', analytics: 'Analytique', settings: 'Paramètres', logout: 'Déconnexion', collections: 'Collections', categories: 'Catégories', inventory: 'Inventaire', customerGroups: 'Groupes de Clients', promotions: 'Promotions', giftCards: 'Cartes Cadeaux', pricing: 'Tarification', regions: 'Régions', shipping: 'Expédition', salesChannels: 'Canaux de Vente', taxes: 'Taxes', payments: 'Paiements', apiKeys: 'Clés API' },
    dashboard: { title: 'Tableau de Bord', subtitle: 'Aperçu des performances de votre magasin', revenue: 'Revenu', orders: 'Commandes', products: 'Produits', customers: 'Clients', totalRevenue: 'Revenu Total', totalOrders: 'Commandes Totales', totalProducts: 'Produits Totaux', totalCustomers: 'Clients Totaux', today: 'aujourd\'hui', activeProducts: 'Produits actifs', registeredUsers: 'Utilisateurs enregistrés', todayPerformance: 'Performance Aujourd\'hui', thisMonth: 'Ce Mois', orderStatusOverview: 'Aperçu du Statut de la Commande', pending: 'En Attente', processing: 'En Cours de Traitement', shipped: 'Expédié', delivered: 'Livré', cancelled: 'Annulé', revenueChange: 'vs période précédente', ordersChange: 'vs période précédente', selectPeriod: 'Sélectionner la Période', thisYear: 'Cette Année', thisWeek: 'Cette Semaine', customRange: 'Plage de Dates Personnalisée', from: 'De', to: 'À', cancel: 'Annuler', applyRange: 'Appliquer la Plage', startDate: 'Date de Début', endDate: 'Date de Fin', applyFilter: 'Appliquer le Filtre', recentOrders: 'Commandes Récentes', topProducts: 'Produits Principaux', orderNumber: 'Commande #', customer: 'Client', date: 'Date', amount: 'Montant', orderStatus: 'Statut', viewAll: 'Voir Tout', order: 'Commande', topSellingProducts: 'Produits Les Plus Vendus', unitsSold: 'unités vendues', revenueLabel: 'Revenu', statusDelivered: 'Livré', statusShipped: 'Expédié', statusProcessing: 'En Cours de Traitement', statusPending: 'En Attente', statusCancelled: 'Annulé', statusCompleted: 'Terminé' },
    products: { title: 'Produits', addProduct: 'Ajouter un Produit', editProduct: 'Modifier le Produit', productName: 'Nom du Produit', description: 'Description', price: 'Prix', stock: 'Stock', sku: 'SKU', activeProduct: 'Produit Actif', createProduct: 'Créer un Produit', updateProduct: 'Mettre à Jour le Produit', deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce produit?', filterPlaceholder: 'Filtrer...', priceFilter: '>520, <850, =30...', allProducts: 'Tous les produits chargés' },
    orders: { title: 'Commandes', orderId: 'ID de Commande', customer: 'Client', date: 'Date', total: 'Total', status: 'Statut', paymentStatus: 'Statut de Paiement', pending: 'En Attente', processing: 'En Cours de Traitement', shipped: 'Expédié', delivered: 'Livré', cancelled: 'Annulé', paid: 'Payé', unpaid: 'Non Payé', failed: 'Échoué', refunded: 'Remboursé', viewDetails: 'Afficher les Détails', updateStatus: 'Mettre à Jour le Statut', filterPlaceholder: 'Filtrer...', totalFilter: '>520, <850, =30...', guest: 'Invité', noRecords: 'Aucun enregistrement', noRecordsDescription: 'Vos commandes apparaîtront ici.', allOrders: 'Toutes les commandes chargées', completed: 'Terminé' },
    users: { title: 'Utilisateurs', userId: 'ID Utilisateur', email: 'Email', fullName: 'Nom Complet', admin: 'Administrateur', active: 'Actif', createdAt: 'Créé', lastOrder: 'Dernière Commande', totalSpent: 'Total Dépensé', addUser: 'Ajouter un Utilisateur', editUser: 'Modifier l\'Utilisateur', deleteConfirm: 'Êtes-vous sûr de vouloir supprimer cet utilisateur?', filterPlaceholder: 'Filtrer...' },
    auth: { login: 'Connexion', logout: 'Déconnexion', email: 'Email', password: 'Mot de Passe', loginButton: 'Se Connecter', loginTitle: 'Connexion Administrateur', loginSubtitle: 'Connectez-vous à votre compte administrateur', invalidCredentials: 'Identifiants invalides', sessionExpired: 'Session expirée. Veuillez vous connecter à nouveau.' },
    messages: { saveSuccess: 'Enregistré avec succès', saveError: 'Erreur lors de l\'enregistrement', deleteSuccess: 'Supprimé avec succès', deleteError: 'Erreur lors de la suppression', loadError: 'Erreur lors du chargement des données', noData: 'Aucune donnée disponible', loadingMore: 'Chargement en cours...', allLoaded: 'Toutes les données chargées' },
    apiKeys: { title: 'Clés API', subtitle: 'Gérez les clés API et les jetons d\'accès', name: 'Nom', key: 'Clé', created: 'Créé', addKey: 'Ajouter une Clé' },
    categories: { title: 'Catégories', subtitle: 'Organisez vos produits', name: 'Nom', slug: 'Slug', description: 'Description', imageUrl: 'URL de l\'Image', edit: 'Modifier', delete: 'Supprimer', addCategory: 'Ajouter une Catégorie', editCategory: 'Modifier la Catégorie', nameRequired: 'Le nom et le slug sont requis', deleteConfirm: 'Êtes-vous sûr de vouloir supprimer cette catégorie?', noDescription: 'Pas de description', noCategories: 'Aucune catégorie trouvée' },
    collections: { title: 'Collections', subtitle: 'Organisez les produits en collections', name: 'Nom', products: 'Produits', status: 'Statut', addCollection: 'Ajouter une Collection' },
    customerGroups: { title: 'Groupes de Clients', subtitle: 'Gérez les groupes et les segments de clients', totalGroups: 'Groupes Totaux', totalSegments: 'Segments Totaux', inGroups: 'Dans les Groupes', inSegments: 'Dans les Segments', createGroup: 'Créer un Groupe', createSegment: 'Créer un Segment' },
    giftCards: { title: 'Cartes Cadeaux', subtitle: 'Gérez les cartes cadeaux et les soldes', code: 'Code', balance: 'Solde', originalValue: 'Valeur Originale', addGiftCard: 'Ajouter une Carte Cadeau' },
    inventory: { title: 'Inventaire', subtitle: 'Gérez les niveaux de stock et les emplacements', product: 'Produit', available: 'Disponible', reserved: 'Réservé', location: 'Emplacement' },
    payments: { title: 'Paiements', subtitle: 'Affichage et gestion de toutes les transactions de paiement', totalPayments: 'Paiements Totaux', totalCaptured: 'Total Capturé', transaction: 'Transaction', amount: 'Montant', date: 'Date' },
    pricing: { title: 'Tarification', subtitle: 'Gérez les listes de prix et les prix spécifiques aux clients', name: 'Nom', type: 'Type', products: 'Produits', addPriceList: 'Ajouter une Liste de Prix' },
    promotions: { title: 'Promotions', subtitle: 'Gérez les remises et les promotions', totalPromotions: 'Promotions Totales', active: 'Actif', expired: 'Expiré', totalUses: 'Utilisations Totales', createPromotion: 'Créer une Promotion' },
    regions: { title: 'Régions', subtitle: 'Gérez les régions géographiques et les devises', name: 'Nom', countries: 'Pays', currency: 'Devise', addRegion: 'Ajouter une Région' },
    salesChannels: { title: 'Canaux de Vente', subtitle: 'Gérez où vos produits sont vendus', name: 'Nom', description: 'Description', products: 'Produits', addChannel: 'Ajouter un Canal' },
    settings: { title: 'Paramètres', subtitle: 'Gérez les paramètres et les préférences de votre magasin', storeDetails: 'Détails du Magasin', storeName: 'Nom du Magasin', storeEmail: 'Email du Magasin', storePhone: 'Téléphone du Magasin', saveChanges: 'Enregistrer les Modifications' },
    shipping: { title: 'Expédition', subtitle: 'Gérez les options et les tarifs d\'expédition', name: 'Nom', region: 'Région', price: 'Prix', addShipping: 'Ajouter une Option d\'Expédition' },
    taxes: { title: 'Taxes', subtitle: 'Gérez les taux et les règles fiscales', name: 'Nom', region: 'Région', rate: 'Taux', addTax: 'Ajouter une Taxe' },
    login: { title: 'Accès Administrateur', subtitle: 'Panneau d\'Administration du Magasin', email: 'Email', password: 'Mot de Passe', loginButton: 'Connexion', forgotPassword: 'Mot de Passe Oublié?' }
  },
  de: {
    common: { loading: 'Laden...', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', add: 'Hinzufügen', create: 'Erstellen', update: 'Aktualisieren', search: 'Suchen', filter: 'Filtern', actions: 'Aktionen', status: 'Status', active: 'Aktiv', inactive: 'Inaktiv', yes: 'Ja', no: 'Nein', back: 'Zurück', next: 'Weiter', previous: 'Zurück', close: 'Schließen', confirm: 'Bestätigen', success: 'Erfolg', error: 'Fehler', warning: 'Warnung' },
    nav: { dashboard: 'Dashboard', products: 'Produkte', orders: 'Bestellungen', customers: 'Kunden', users: 'Benutzer', analytics: 'Analytik', settings: 'Einstellungen', logout: 'Abmelden', collections: 'Sammlungen', categories: 'Kategorien', inventory: 'Bestand', customerGroups: 'Kundengruppen', promotions: 'Aktionen', giftCards: 'Geschenkkarten', pricing: 'Preisgestaltung', regions: 'Regionen', shipping: 'Versand', salesChannels: 'Vertriebskanäle', taxes: 'Steuern', payments: 'Zahlungen', apiKeys: 'API-Schlüssel' },
    dashboard: { title: 'Dashboard', subtitle: 'Übersicht der Leistung Ihres Ladens', revenue: 'Umsatz', orders: 'Bestellungen', products: 'Produkte', customers: 'Kunden', totalRevenue: 'Gesamtumsatz', totalOrders: 'Gesamtbestellungen', totalProducts: 'Gesamtprodukte', totalCustomers: 'Gesamtkunden', today: 'heute', activeProducts: 'Aktive Produkte', registeredUsers: 'Registrierte Benutzer', todayPerformance: 'Heutige Leistung', thisMonth: 'Dieser Monat', orderStatusOverview: 'Übersicht des Bestellstatus', pending: 'Ausstehend', processing: 'In Bearbeitung', shipped: 'Versendet', delivered: 'Geliefert', cancelled: 'Storniert', revenueChange: 'vs Vorperiode', ordersChange: 'vs Vorperiode', selectPeriod: 'Zeitraum auswählen', thisYear: 'Dieses Jahr', thisWeek: 'Diese Woche', customRange: 'Benutzerdefinierter Datumsbereich', from: 'Von', to: 'Bis', cancel: 'Abbrechen', applyRange: 'Bereich anwenden', startDate: 'Startdatum', endDate: 'Enddatum', applyFilter: 'Filter anwenden', recentOrders: 'Aktuelle Bestellungen', topProducts: 'Top-Produkte', orderNumber: 'Bestellung #', customer: 'Kunde', date: 'Datum', amount: 'Betrag', orderStatus: 'Status', viewAll: 'Alle anzeigen', order: 'Bestellung', topSellingProducts: 'Meistverkaufte Produkte', unitsSold: 'verkaufte Einheiten', revenueLabel: 'Umsatz', statusDelivered: 'Geliefert', statusShipped: 'Versendet', statusProcessing: 'In Bearbeitung', statusPending: 'Ausstehend', statusCancelled: 'Storniert', statusCompleted: 'Abgeschlossen' },
    products: { title: 'Produkte', addProduct: 'Produkt hinzufügen', editProduct: 'Produkt bearbeiten', productName: 'Produktname', description: 'Beschreibung', price: 'Preis', stock: 'Bestand', sku: 'SKU', activeProduct: 'Aktives Produkt', createProduct: 'Produkt erstellen', updateProduct: 'Produkt aktualisieren', deleteConfirm: 'Sind Sie sicher, dass Sie dieses Produkt löschen möchten?', filterPlaceholder: 'Filtern...', priceFilter: '>520, <850, =30...', allProducts: 'Alle Produkte geladen' },
    orders: { title: 'Bestellungen', orderId: 'Bestellnummer', customer: 'Kunde', date: 'Datum', total: 'Gesamt', status: 'Status', paymentStatus: 'Zahlungsstatus', pending: 'Ausstehend', processing: 'In Bearbeitung', shipped: 'Versendet', delivered: 'Geliefert', cancelled: 'Storniert', paid: 'Bezahlt', unpaid: 'Unbezahlt', failed: 'Fehlgeschlagen', refunded: 'Erstattet', viewDetails: 'Details anzeigen', updateStatus: 'Status aktualisieren', filterPlaceholder: 'Filtern...', totalFilter: '>520, <850, =30...', guest: 'Gast', noRecords: 'Keine Aufzeichnungen', noRecordsDescription: 'Ihre Bestellungen werden hier angezeigt.', allOrders: 'Alle Bestellungen geladen', completed: 'Abgeschlossen' },
    users: { title: 'Benutzer', userId: 'Benutzer-ID', email: 'E-Mail', fullName: 'Vollständiger Name', admin: 'Administrator', active: 'Aktiv', createdAt: 'Erstellt', lastOrder: 'Letzte Bestellung', totalSpent: 'Gesamt Ausgegeben', addUser: 'Benutzer hinzufügen', editUser: 'Benutzer bearbeiten', deleteConfirm: 'Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?', filterPlaceholder: 'Filtern...' },
    auth: { login: 'Anmelden', logout: 'Abmelden', email: 'E-Mail', password: 'Passwort', loginButton: 'Anmelden', loginTitle: 'Administrator-Anmeldung', loginSubtitle: 'Melden Sie sich bei Ihrem Admin-Konto an', invalidCredentials: 'Ungültige Anmeldedaten', sessionExpired: 'Sitzung abgelaufen. Bitte melden Sie sich erneut an.' },
    messages: { saveSuccess: 'Erfolgreich gespeichert', saveError: 'Fehler beim Speichern', deleteSuccess: 'Erfolgreich gelöscht', deleteError: 'Fehler beim Löschen', loadError: 'Fehler beim Laden der Daten', noData: 'Keine Daten verfügbar', loadingMore: 'Lade mehr...', allLoaded: 'Alle Daten geladen' },
    apiKeys: { title: 'API-Schlüssel', subtitle: 'API-Schlüssel und Zugriffstoken verwalten', name: 'Name', key: 'Schlüssel', created: 'Erstellt', addKey: 'Schlüssel hinzufügen' },
    categories: { title: 'Kategorien', subtitle: 'Organisieren Sie Ihre Produkte', name: 'Name', slug: 'Slug', description: 'Beschreibung', imageUrl: 'Bild-URL', edit: 'Bearbeiten', delete: 'Löschen', addCategory: 'Kategorie hinzufügen', editCategory: 'Kategorie bearbeiten', nameRequired: 'Name und Slug sind erforderlich', deleteConfirm: 'Sind Sie sicher, dass Sie diese Kategorie löschen möchten?', noDescription: 'Keine Beschreibung', noCategories: 'Keine Kategorien gefunden' },
    collections: { title: 'Sammlungen', subtitle: 'Organisieren Sie Produkte in Sammlungen', name: 'Name', products: 'Produkte', status: 'Status', addCollection: 'Sammlung hinzufügen' },
    customerGroups: { title: 'Kundengruppen', subtitle: 'Verwalten Sie Kundengruppen und Segmente', totalGroups: 'Gesamtgruppen', totalSegments: 'Gesamtsegmente', inGroups: 'In Gruppen', inSegments: 'In Segmenten', createGroup: 'Gruppe erstellen', createSegment: 'Segment erstellen' },
    giftCards: { title: 'Geschenkkarten', subtitle: 'Verwalten Sie Geschenkkarten und Guthaben', code: 'Code', balance: 'Guthaben', originalValue: 'Ursprünglicher Wert', addGiftCard: 'Geschenkkarte hinzufügen' },
    inventory: { title: 'Bestand', subtitle: 'Verwalten Sie Lagerbestände und Standorte', product: 'Produkt', available: 'Verfügbar', reserved: 'Reserviert', location: 'Standort' },
    payments: { title: 'Zahlungen', subtitle: 'Alle Zahlungstransaktionen anzeigen und verwalten', totalPayments: 'Gesamtzahlungen', totalCaptured: 'Gesamt erfasst', transaction: 'Transaktion', amount: 'Betrag', date: 'Datum' },
    pricing: { title: 'Preisgestaltung', subtitle: 'Verwalten Sie Preislisten und kundespezifische Preise', name: 'Name', type: 'Typ', products: 'Produkte', addPriceList: 'Preisliste hinzufügen' },
    promotions: { title: 'Aktionen', subtitle: 'Verwalten Sie Rabatte und Aktionen', totalPromotions: 'Gesamtaktionen', active: 'Aktiv', expired: 'Abgelaufen', totalUses: 'Gesamtnutzungen', createPromotion: 'Aktion erstellen' },
    regions: { title: 'Regionen', subtitle: 'Verwalten Sie geografische Regionen und Währungen', name: 'Name', countries: 'Länder', currency: 'Währung', addRegion: 'Region hinzufügen' },
    salesChannels: { title: 'Vertriebskanäle', subtitle: 'Verwalten Sie, wo Ihre Produkte verkauft werden', name: 'Name', description: 'Beschreibung', products: 'Produkte', addChannel: 'Kanal hinzufügen' },
    settings: { title: 'Einstellungen', subtitle: 'Verwalten Sie die Laden- und Präferenzeinstellungen', storeDetails: 'Laden-Details', storeName: 'Ladenname', storeEmail: 'Laden-E-Mail', storePhone: 'Laden-Telefon', saveChanges: 'Änderungen speichern' },
    shipping: { title: 'Versand', subtitle: 'Verwalten Sie Versandoptionen und Tarife', name: 'Name', region: 'Region', price: 'Preis', addShipping: 'Versandoption hinzufügen' },
    taxes: { title: 'Steuern', subtitle: 'Verwalten Sie Steuersätze und Regeln', name: 'Name', region: 'Region', rate: 'Satz', addTax: 'Steuer hinzufügen' },
    login: { title: 'Administrator-Anmeldung', subtitle: 'Shop-Verwaltungspanel', email: 'E-Mail', password: 'Passwort', loginButton: 'Anmelden', forgotPassword: 'Passwort vergessen?' }
  }
}

export const getTranslations = (language: Language = 'en'): Translations => {
  return translations[language] || translations.en
}

export const availableLanguages: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
]

export const getBrowserLanguage = (): Language => {
  if (typeof window === 'undefined') return 'en'
  const browserLang = navigator.language.split('-')[0] as Language
  return ['en', 'es', 'it', 'fr', 'de'].includes(browserLang) ? browserLang : 'en'
}
